CREATE USER panchita IDENTIFIED BY  soyAngelDB2024;
GRANT CREATE SESSION TO panchita ;
GRANT CREATE TABLE TO panchita;
GRANT CREATE VIEW TO panchita;
GRANT CREATE PROCEDURE TO panchita;
GRANT CREATE TRIGGER TO panchita;
GRANT CREATE SEQUENCE TO panchita;
GRANT CREATE SYNONYM TO panchita;
GRANT UNLIMITED TABLESPACE TO panchita;